[package]
name = "tetris-clone"
version = "0.1.0"
authors = ["nicey <nicey@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
